# Generated by Django 5.0.1 on 2024-01-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month1', models.IntegerField()),
                ('month2', models.IntegerField()),
                ('month3', models.IntegerField()),
                ('month4', models.IntegerField()),
                ('prediction_value', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
